
const fs = require('fs');
const pretty = require('../titan-control-system/client/src/pretty.json');

var readme_output = '<!-- This file is generated by ./build-readme.js. Do not modify it directly. -->\n\n';
var srcs = [ 'readme.src.md' ];

for(var i=0; i<srcs.length; i++) {
  var src = fs.readFileSync(srcs[i]).toString();
  console.log(src)
  for(var key in pretty) {
    var val = pretty[key];
    // Use a negative lookahead so that if a tagname is surrounded by double backticks, it will not be prettified.
    var re = new RegExp('`' + key + '`(?!`)', 'g');
    src = src.replace(re, '`'+val+'`');
  }
  readme_output += src + '\n\n';
}

console.log(readme_output);

fs.writeFileSync('README.md', readme_output);
